version: '3'

services:
  webapp:
    container_name: deep-dream-maker-webapp
    build:
      context: './webapp'
      dockerfile: Dockerfile
    depends_on:
      - server
    volumes:
      - './webapp:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  server:
   container_name: deep-dream-maker-server
   build: 
     context: './server'
     dockerfile: Dockerfile
   volumes:
     - './server:/app'
   ports: 
     - 3002:5000
   environment:
     - NVIDIA_VISIBLE_DEVICES=all
     - FLASK_DEBUG=1
     - PYTHONUNBUFFERED=1
     - FLASK_ENV=development


  

