version: '3'

services:
  webapp:
    image: deep-dream-maker-webapp:dev
    container_name: deep-dream-maker-webapp
    build:
      context: './webapp'
      dockerfile: Dockerfile
    volumes:
      - './webapp:/app'
      - '/app/node_modules'
    ports:
      - 7777:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  
  server:
    image: deep-dream-maker-server:dev
    container_name: deep-dream-maker-server
    build:
      context: './server'
      dockerfile: Dockerfile
    volumes:
      - './server:/app'
    ports: 
      - 6001:5000
    environment:
     - PYTHONUNBUFFERED=1
  

